import {Metadata} from 'next';
import Link from 'next/link';
import {ActivityIcon,BoltIcon,GaugeIcon,LeagueIcon,RouteIcon,TargetIcon} from '@/app/components/ui-icons';

export const metadata:Metadata={title:'ElectroQuest | Home'};
const features=[
 {icon:RouteIcon,title:'Adaptive journey',text:'A long-term learning path that responds to your mastery and pace.'},
 {icon:ActivityIcon,title:'Reasoning feedback',text:'Clear feedback identifies misconceptions after every answer.'},
 {icon:GaugeIcon,title:'Mastery tracking',text:'See measurable progress across electrical engineering topics.'},
 {icon:BoltIcon,title:'Focused sessions',text:'Complete structured 20-question units without distractions.'},
 {icon:TargetIcon,title:'Weekly goals',text:'Build consistency through practical targets and streaks.'},
 {icon:LeagueIcon,title:'Weekly Leaderboard',text:'Compete on skill, accuracy, difficulty, and response speed.'},
];

export default function Home(){return <div className="min-h-screen bg-[#f6f7f9] text-slate-950">
 <nav className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><div className="flex items-center gap-3 font-black"><span className="brand-mark"><BoltIcon/></span>ElectroQuest</div><div className="flex items-center gap-3"><Link href="/login" className="px-3 py-2 font-semibold text-slate-600">Login</Link><Link href="/register" className="btn-primary">Create account</Link></div></div></nav>
 <main><section className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-20 lg:grid-cols-[1.15fr_.85fr] lg:py-28"><div><p className="eyebrow">Adaptive electrical engineering practice</p><h1 className="mt-4 max-w-3xl text-5xl font-black leading-[1.05] tracking-tight sm:text-6xl">Build engineering skill, one challenge at a time.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Learn through focused sessions, adaptive difficulty, and a competitive weekly league designed for long-term progress.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register" className="btn-primary px-7 py-3.5">Start learning</Link><Link href="/login" className="btn-secondary px-7 py-3.5">Continue your journey</Link></div></div><div className="rounded-3xl border border-slate-800 bg-[#101b2d] p-7 text-white shadow-[0_16px_45px_rgba(15,23,42,.15)]"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-300">Today&apos;s session</p><span className="rounded-lg border border-slate-600 px-2.5 py-1 text-xs">20 questions</span></div><h2 className="mt-7 text-2xl font-black">Circuit Analysis Foundations</h2><p className="mt-2 text-slate-400">Warm-up · Adaptive difficulty</p><div className="mt-8 h-2 rounded-full bg-slate-700"><div className="h-full w-2/5 rounded-full bg-blue-500"/></div><div className="mt-3 flex justify-between text-xs text-slate-400"><span>8 completed</span><span>12 remaining</span></div><div className="mt-8 grid grid-cols-3 gap-2">{['Accuracy','XP','Streak'].map((x,i)=><div key={x} className="rounded-xl border border-slate-700 bg-[#17243a] p-3"><strong>{[86,240,7][i]}{i===0?'%':''}</strong><p className="mt-1 text-[11px] text-slate-400">{x}</p></div>)}</div></div></section>
 <section id="features" className="border-y border-slate-200 bg-white py-20"><div className="mx-auto max-w-6xl px-5"><p className="eyebrow">Built for progress</p><h2 className="mt-2 text-3xl font-black">Everything supports the learning loop</h2><div className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-slate-200 bg-slate-200 md:grid-cols-3">{features.map(({icon:Icon,title,text})=><article key={title} className="bg-white p-7"><div className="grid h-10 w-10 place-items-center rounded-lg bg-blue-50 text-blue-600"><Icon/></div><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>
 <section className="bg-[#101b2d] py-16 text-white"><div className="mx-auto flex max-w-4xl flex-col items-center px-5 text-center"><h2 className="text-3xl font-black">Ready to begin?</h2><p className="mt-3 text-slate-300">Start your electrical engineering journey today.</p><Link href="/register" className="mt-7 rounded-xl bg-blue-600 px-8 py-3.5 font-bold hover:bg-blue-500">Create free account</Link></div></section></main>
 <footer className="border-t border-slate-800 bg-[#101b2d] py-7 text-center text-sm text-slate-500">ElectroQuest · Adaptive electrical engineering practice</footer>
 </div>}
