"""Extensible Electrical Engineering journey map.

The entries are curriculum metadata, not copied textbook exercises. Order reflects
prerequisite progression while the adaptive engine may revisit any unlocked topic.
"""

SEMESTER_COURSES = [
    (1,"MAS1101",4,"Matematika Dasar I","basic-mathematics",["Arithmetic and fractions","Algebra foundations","Geometry and trigonometry","Functions and graphs"]),
    (1,"FIS1101",4,"Fisika Dasar IA","basic-physics",["Units and measurement","Motion and force","Work energy and power","Waves and basic electricity"]),
    (1,"KUS1102",2,"Pembentukan Karakter Del","character-development",["Integrity and discipline","Teamwork","Leadership fundamentals"]),
    (1,"KUS1103",3,"Bahasa Inggris I","english-i",["Technical vocabulary","Reading comprehension","Engineering communication"]),
    (1,"KIS1201",3,"Kimia Dasar B","basic-chemistry",["Atomic structure","Chemical bonding","Electrochemistry","Engineering materials"]),
    (1,"KUS1001",2,"Bahasa Indonesia","indonesian-language",["Scientific writing","Effective sentences","Technical reports"]),
    (1,"KUS0101",2,"Penyelesaian Masalah di Dunia Digital","digital-problem-solving",["Computational thinking","Problem decomposition","Data and digital ethics"]),
    (2,"MAS1201",4,"Matematika Dasar II","basic-mathematics-ii",["Limits and continuity","Differential calculus","Integral calculus","Sequences and series"]),
    (2,"KUS1202",2,"Pengantar Rekayasa dan Desain","engineering-design",["Engineering design process","Requirements and constraints","Prototyping","Design communication"]),
    (2,"10S1001",3,"Matematika Diskrit","discrete-mathematics",["Logic and proof","Sets and relations","Combinatorics","Graphs and trees"]),
    (2,"10S1201",3,"Pemrograman Prosedural","procedural-programming",["Variables and input output","Conditions and loops","Functions","Arrays and strings"]),
    (2,"13S1201",2,"Pengantar Analisis Rangkaian","circuit-fundamentals",["Charge current and voltage","Resistance and power","Ohm's law","Series and parallel circuits"]),
    (2,"KUS0001",2,"Pancasila","pancasila",["National foundations","Civic values","Applied ethics"]),
    (3,"MAS2101",3,"Probabilitas dan Statistika","probability-statistics",["Probability models","Random variables","Descriptive statistics","Statistical inference"]),
    (3,"13S2101",3,"Sistem Digital","digital-electronics",["Boolean algebra","Combinational logic","Sequential logic","Data converters"]),
    (3,"13S2102",1,"Praktikum Sistem Digital","digital-electronics-lab",["Logic gate experiments","Combinational design lab","Sequential design lab"]),
    (3,"13S2103",3,"Matematika Teknik I","engineering-mathematics",["Algebra and equations","Complex numbers","Differential equations","Matrices and numerical methods"]),
    (3,"13S2104",3,"Rangkaian Elektrik","circuit-analysis",["KCL and node voltage","KVL and mesh current","Thevenin and Norton","Superposition"]),
    (3,"13S2105",1,"Praktikum Rangkaian Elektrik","circuit-analysis-lab",["Instrument setup","DC circuit verification","AC circuit measurement","Lab reporting"]),
    (3,"10S1003",3,"Basis Data","database-fundamentals",["Relational models","SQL queries","Normalization","Transactions"]),
    (3,"13S2107",1,"Praktikum Pemrograman Berorientasi Objek","oop-lab",["Class implementation lab","Inheritance lab","Composition project"]),
    (3,"13S2106",2,"Pemrograman Berorientasi Objek","object-oriented-programming",["Classes and objects","Encapsulation","Inheritance and polymorphism","Interfaces and composition"]),
    (4,"13S2201",2,"Sistem Instrumentasi","instrumentation-sensors",["Sensor characteristics","Signal conditioning","Data acquisition","Measurement systems"]),
    (4,"13S2202",1,"Praktikum Sistem Instrumentasi","instrumentation-lab",["Sensor calibration","Signal conditioning lab","DAQ experiments"]),
    (4,"13S2203",3,"Elektronika I","electronics-i",["Diodes and rectifiers","BJT operation","BJT biasing","Common emitter amplifiers"]),
    (4,"13S2204",1,"Praktikum Elektronika I","electronics-i-lab",["Diode characterization","BJT bias lab","Amplifier measurement"]),
    (4,"13S2205",3,"Matematika Teknik II","engineering-mathematics-ii",["Fourier series","Laplace transforms","Vector calculus","Partial differential equations"]),
    (4,"13S2206",2,"Elektromagnetik","electromagnetics",["Electric fields","Magnetic fields","Maxwell equations","Electromagnetic waves"]),
    (4,"10S2001",3,"Jaringan Komputer","computer-networks",["Network fundamentals","OSI and TCP-IP","IPv4 addressing and subnetting","Routing and network services"]),
    (4,"13S2207",3,"Teknik Visualisasi Interaktif","interactive-visualization",["Visual data principles","Interactive interfaces","Engineering visualization"]),
    (5,"13S3101",3,"Arsitektur Sistem Komputer","computer-architecture",["Instruction set architecture","CPU datapath","Memory hierarchy","Input output systems"]),
    (5,"13S3102",1,"Praktikum Arsitektur Sistem Komputer","computer-architecture-lab",["Assembly lab","Datapath simulation","Memory experiments"]),
    (5,"13S3103",3,"Sinyal dan Sistem","signals-and-systems",["Signal classification","Convolution","Fourier analysis","Laplace transforms"]),
    (5,"13S3104",2,"Sistem Tenaga Elektrik","power-system-fundamentals",["Generation transmission distribution","Single-line diagrams","Power system components","Three-phase power"]),
    (5,"13S3111",3,"Elektronika II","electronics-ii",["MOSFET operation","MOSFET biasing","Operational amplifiers","Multistage amplifiers"]),
    (5,"13S3112",1,"Praktikum Elektronika II","electronics-ii-lab",["MOSFET characterization","Op-amp lab","Multistage amplifier lab"]),
    (5,"13S3121",3,"Antar Jaringan","internetworking",["Subnet design","Static and dynamic routing","VLAN and switching","Network troubleshooting"]),
    (5,"13S3122",1,"Praktikum Antar Jaringan","internetworking-lab",["Router configuration","VLAN lab","Routing protocol lab"]),
    (5,"10S2002",3,"Sistem Operasi","operating-systems",["Processes and threads","Memory management","File systems","Concurrency"]),
    (5,"KUS0203",2,"Kewarganegaraan","civics",["Citizenship","Law and responsibility","Technology and society"]),
    (6,"13S3201",3,"Pengolahan Sinyal Digital","digital-signal-processing",["Sampling and quantization","Discrete transforms","Digital filters","Spectral analysis"]),
    (6,"13S3202",1,"Praktikum Pengolahan Sinyal Digital","dsp-lab",["Sampling lab","FFT experiments","Digital filter implementation"]),
    (6,"13S3203",3,"Sistem Mikrokontroler","embedded-systems",["Microcontroller architecture","Digital IO","Timers and interrupts","Serial communication"]),
    (6,"13S3204",1,"Praktikum Sistem Mikrokontroler","embedded-systems-lab",["GPIO lab","Timer and interrupt lab","Peripheral integration"]),
    (6,"13S3211",3,"Sistem Kendali","control-systems",["Transfer functions","Time response","Stability","PID control"]),
    (6,"13S3212",1,"Praktikum Sistem Kendali","control-systems-lab",["Plant modeling lab","PID tuning","Closed-loop experiments"]),
    (6,"13S3221",3,"Komputasi Awan","cloud-computing",["Virtualization","Cloud service models","Containers","Cloud architecture"]),
    (6,"13S3222",1,"Praktikum Komputasi Awan","cloud-computing-lab",["Container deployment","Cloud networking","Service monitoring"]),
    (6,"10S3001",3,"Kecerdasan Buatan","artificial-intelligence",["Search and reasoning","Machine learning fundamentals","Neural networks","Engineering AI applications"]),
    (6,"KUS3201",3,"Bahasa Inggris II","english-ii",["Technical presentations","Research writing","Professional communication"]),
    (7,"TIS0001",3,"Kewirausahaan","entrepreneurship",["Opportunity discovery","Business models","Engineering product strategy"]),
    (7,"13S4093",3,"Tugas Akhir II","final-project",["Research execution","Engineering validation","Thesis communication"]),
    (7,"13S4201",2,"Etika Profesional","professional-ethics",["Engineering responsibility","Safety and risk","Professional conduct"]),
    (7,"13S4280",2,"Analisis Dampak Lingkungan","environmental-impact",["Environmental assessment","Sustainability metrics","Engineering mitigation"]),
    (7,"13S4011",3,"Sistem Kendali Digital","digital-control",["Discrete system models","Digital controllers","State-space implementation"]),
    (7,"13S4012",3,"Robotika","robotics",["Robot kinematics","Sensors and actuators","Motion planning","Robot control"]),
    (7,"13S4014",3,"Pengolahan Citra Digital","digital-image-processing",["Image representation","Spatial filtering","Segmentation","Feature extraction"]),
    (7,"13S4015",3,"Sistem Kendali Multivariabel","multivariable-control",["State-space systems","Controllability","Observers","MIMO control"]),
    (7,"13S4016",3,"Mekatronika","mechatronics",["Mechanical-electrical integration","Actuators and drives","Embedded control","System integration"]),
    (7,"13S4017",3,"Energi Terbarukan","renewable-energy",["Solar PV","Wind energy","Energy storage","Grid integration"]),
    (7,"13S4021",3,"Jaringan Sensor Nirkabel","wireless-sensor-networks",["Sensor node architecture","Wireless protocols","Energy efficiency","IoT integration"]),
    (7,"13S4022",3,"Jaringan Terdistribusi","distributed-networks",["Distributed protocols","Consensus basics","Resilience","Network synchronization"]),
    (7,"13S4023",3,"Komputasi Paralel dan Terdistribusi","parallel-distributed-computing",["Parallel architectures","Concurrency models","Distributed computation","Performance analysis"]),
    (7,"13S4024",3,"Monitoring and Cloud System Security","cloud-monitoring-security",["Observability","Identity and access","Threat detection","Incident response"]),
    (7,"13S4025",3,"Administrasi Sistem Cloud","cloud-administration",["Cloud resource administration","Automation","Reliability","Cost control"]),
    (7,"KUS0002",2,"Agama Kristen","christian-religion",["Faith and character","Ethics and responsibility","Interfaith respect"]),
    (7,"KUS0003",2,"Agama Katolik","catholic-religion",["Faith and character","Ethics and responsibility","Interfaith respect"]),
    (7,"KUS0004",2,"Agama Islam","islamic-religion",["Faith and character","Ethics and responsibility","Interfaith respect"]),
]

COURSE_METADATA = {slug: {"semester": semester, "code": code, "credits": credits} for semester, code, credits, name, slug, topics in SEMESTER_COURSES}

EXTENDED_CURRICULUM = [
    ("Basic Mathematics", "basic-mathematics", ["Arithmetic and fractions", "Algebra foundations", "Geometry and trigonometry", "Functions and graphs"]),
    ("Basic Physics", "basic-physics", ["Units and measurement", "Motion and force", "Work energy and power", "Waves and basic electricity"]),
    ("Engineering Mathematics", "engineering-mathematics", ["Algebra and equations", "Complex numbers", "Differential equations", "Matrices and numerical methods"]),
    ("Circuit Fundamentals", "circuit-fundamentals", ["Charge current and voltage", "Resistance and power", "Ohm's law", "Series and parallel circuits"]),
    ("Circuit Analysis", "circuit-analysis", ["KCL and node voltage", "KVL and mesh current", "Thevenin and Norton", "Superposition"]),
    ("Transient Circuits", "transient-circuits", ["RC transients", "RL transients", "RLC response", "Initial and final conditions"]),
    ("AC Circuits", "ac-circuits", ["Sinusoids and phasors", "Complex impedance", "AC power", "Resonance"]),
    ("Three-Phase Systems", "three-phase-systems", ["Wye and delta", "Line and phase quantities", "Balanced power", "Unbalanced loads"]),
    ("Analog Electronics", "analog-electronics", ["Diodes", "Rectifiers", "Bias and small signal", "Frequency response"]),
    ("Electronics I", "electronics-i", ["BJT operation", "BJT biasing", "Common emitter amplifiers"]),
    ("Electronics II", "electronics-ii", ["MOSFET operation", "MOSFET biasing", "Multistage amplifiers"]),
    ("Operational Amplifiers", "operational-amplifiers", ["Ideal op-amp", "Inverting and non-inverting", "Filters and integrators"]),
    ("Digital Electronics", "digital-electronics", ["Boolean algebra", "Combinational logic", "Sequential logic", "Data converters"]),
    ("Signals and Systems", "signals-and-systems", ["Signal classification", "Convolution", "Fourier analysis", "Laplace transforms"]),
    ("Electrical Measurements", "electrical-measurements", ["Measurement uncertainty", "Voltage and current measurement", "Power measurement"]),
    ("Instrumentation and Sensors", "instrumentation-sensors", ["Sensor characteristics", "Signal conditioning", "Data acquisition"]),
    ("Electromagnetics", "electromagnetics", ["Electric fields", "Magnetic fields", "Maxwell equations", "Electromagnetic waves"]),
    ("Control Systems", "control-systems", ["Transfer functions", "Time response", "Stability", "PID control"]),
    ("Computer Networks", "computer-networks", ["Network fundamentals", "OSI and TCP-IP", "IPv4 addressing and subnetting", "Routing and network services"]),
    ("Procedural Programming", "procedural-programming", ["Variables and input output", "Conditions and loops", "Functions", "Arrays and strings"]),
    ("Object-Oriented Programming", "object-oriented-programming", ["Classes and objects", "Encapsulation", "Inheritance and polymorphism", "Interfaces and composition"]),
    ("Data Structures and Algorithms", "data-structures-algorithms", ["Linear data structures", "Searching and sorting", "Recursion", "Algorithm complexity"]),
    ("Database Fundamentals", "database-fundamentals", ["Relational models", "SQL queries", "Normalization", "Transactions"]),
    ("Embedded Systems", "embedded-systems", ["Microcontroller architecture", "Digital IO", "Timers and interrupts", "Serial communication"]),
    ("Electrical Machines", "electrical-machines", ["Magnetic circuits", "DC machines", "Transformers", "Induction machines", "Synchronous machines"]),
    ("Power Electronics", "power-electronics", ["Power semiconductor devices", "Controlled rectifiers", "DC-DC converters", "Inverters"]),
    ("Power System Fundamentals", "power-system-fundamentals", ["Generation transmission distribution", "Single-line diagrams", "Power system components"]),
    ("Per-Unit Systems", "per-unit-systems", ["Base quantities", "Base conversion", "Per-unit network models"]),
    ("Transmission Lines", "transmission-lines", ["Line parameters", "Short and medium lines", "Long lines", "Voltage regulation"]),
    ("Power Flow", "power-flow", ["Bus classification", "Ybus construction", "Gauss-Seidel", "Newton-Raphson"]),
    ("Economic Dispatch", "economic-dispatch", ["Generator cost curves", "Incremental cost", "Loss coordination"]),
    ("Fault Analysis", "fault-analysis", ["Symmetrical components", "Three-phase faults", "SLG LL and DLG faults"]),
    ("Power System Protection", "power-system-protection", ["Protection zones", "Overcurrent relays", "Distance protection", "Differential protection"]),
    ("Power System Stability", "power-system-stability", ["Rotor dynamics", "Equal area criterion", "Transient stability"]),
    ("Power Quality", "power-quality", ["Harmonics", "Voltage sag and swell", "Power factor correction"]),
    ("Renewable Energy", "renewable-energy", ["Solar PV", "Wind energy", "Energy storage", "Grid integration"]),
    ("Smart Grid", "smart-grid", ["Advanced metering", "Demand response", "Distributed energy resources"]),
    ("Distribution Systems", "distribution-systems", ["Radial feeders", "Voltage drop", "Distribution protection", "Reliability"]),
    ("Industrial Electrical Systems", "industrial-electrical-systems", ["Motor starting", "Industrial loads", "Grounding", "Electrical safety"]),
]

# The campus list is only a coverage reference. ElectroQuest deliberately exposes
# game-like learning zones, not semesters, course codes, credits, or separate labs.
ZONE_NAMES = {
    "basic-mathematics": "Math Foundations",
    "basic-physics": "Physics Foundations",
    "engineering-mathematics": "Engineering Math Toolkit",
    "circuit-fundamentals": "Circuit Starter Lab",
    "circuit-analysis": "Circuit Analysis Arena",
    "digital-electronics": "Digital Logic Workshop",
    "instrumentation-sensors": "Sensors and Measurement Lab",
    "electromagnetics": "Fields and Waves",
    "signals-and-systems": "Signals Lab",
    "control-systems": "Control and Automation",
    "computer-networks": "Connected Systems",
    "procedural-programming": "Code Foundations",
    "object-oriented-programming": "Object-Oriented Code Lab",
    "data-structures-algorithms": "Algorithms Workshop",
    "database-fundamentals": "Data Systems",
    "embedded-systems": "Embedded Systems Lab",
    "electrical-machines": "Electrical Machines Workshop",
    "power-system-fundamentals": "Power Grid Foundations",
    "renewable-energy": "Renewable Energy Lab",
}
CURRICULUM = [(ZONE_NAMES.get(slug, name), slug, topics) for name, slug, topics in EXTENDED_CURRICULUM]
CURRICULUM += [
    ("Computer Architecture Lab", "computer-architecture", ["Processor and instructions", "CPU datapath", "Memory hierarchy", "Input output systems"]),
    ("Operating Systems", "operating-systems", ["Processes and threads", "Memory management", "File systems", "Concurrency"]),
    ("Digital Signal Workshop", "digital-signal-processing", ["Sampling and quantization", "Discrete transforms", "Digital filters", "Spectral analysis"]),
    ("Cloud and Edge Systems", "cloud-computing", ["Virtualization", "Containers", "Cloud architecture", "Edge integration"]),
    ("Engineering AI", "artificial-intelligence", ["Search and reasoning", "Machine learning fundamentals", "Neural networks", "Engineering AI applications"]),
    ("Robotics Lab", "robotics", ["Robot kinematics", "Sensors and actuators", "Motion planning", "Robot control"]),
    ("Vision Systems", "digital-image-processing", ["Image representation", "Spatial filtering", "Segmentation", "Feature extraction"]),
    ("Mechatronics Lab", "mechatronics", ["Mechanical-electrical integration", "Actuators and drives", "Embedded control", "System integration"]),
    ("Wireless Sensor Networks", "wireless-sensor-networks", ["Sensor node architecture", "Wireless protocols", "Energy efficiency", "IoT integration"]),
    ("Distributed and Cloud Security", "cloud-monitoring-security", ["Distributed systems", "Observability", "Identity and access", "Incident response"]),
]


# Original starter items used by the adaptive engine. More variants can be added
# without changing the journey API or schema.
STARTER_QUESTIONS = [
    ("engineering-mathematics", "Algebra and equations", "Solve an engineering equation", "Solve 3x + 5 = 20.", "5", [], 0.001, "easy"),
    ("engineering-mathematics", "Algebra and equations", "Rearrange a linear model", "Solve 4x - 8 = 24.", "8", [], 0.001, "easy"),
    ("engineering-mathematics", "Algebra and equations", "Evaluate a squared quantity", "If x = 3, evaluate 2x^2 + 1.", "19", [], 0.001, "medium"),
    ("engineering-mathematics", "Complex numbers", "Magnitude of a complex quantity", "Find the magnitude of 3 + j4.", "5", [], 0.001, "easy"),
    ("engineering-mathematics", "Complex numbers", "Real component addition", "Find the real component of (3 + j2) + (4 - j5).", "7", [], 0.001, "easy"),
    ("engineering-mathematics", "Complex numbers", "Complex magnitude practice", "Find the magnitude of 5 + j12.", "13", [], 0.001, "medium"),
    ("engineering-mathematics", "Differential equations", "First derivative", "For y = 3x^2, find dy/dx at x = 2.", "12", [], 0.001, "easy"),
    ("engineering-mathematics", "Differential equations", "Exponential decay rate", "For y = exp(-2t), find dy/dt at t = 0.", "-2", [], 0.001, "medium"),
    ("engineering-mathematics", "Matrices and numerical methods", "Two by two determinant", "Find the determinant of the matrix [[2, 1], [3, 4]].", "5", [], 0.001, "easy"),
    ("engineering-mathematics", "Matrices and numerical methods", "Matrix row sum", "Find the sum of the first row of matrix [[4, -1], [2, 3]].", "3", [], 0.001, "easy"),
    ("circuit-fundamentals", "Ohm's law", "Find current from voltage and resistance", "A 24 V source is connected to a 12 ohm resistor. Find the current.", "2 A", ["A", "mA"], 0.001, "easy"),
    ("circuit-fundamentals", "Resistance and power", "Electrical power", "A component has 12 V across it and carries 2 A. Find absorbed power using P = VI.", "24 W", ["W", "kW"], 0.01, "easy"),
    ("circuit-fundamentals", "Series and parallel circuits", "Series resistance", "Two series resistors are 10 ohm and 15 ohm. Find total resistance.", "25 ohm", ["ohm", "kohm"], 0.01, "easy"),
    ("circuit-analysis", "KCL and node voltage", "Apply KCL", "A node receives 5 A and 2 A. If 4 A leaves through one branch, find the remaining outgoing current.", "3 A", ["A", "mA"], 0.001, "easy"),
    ("circuit-analysis", "KVL and mesh current", "Apply KVL", "An 18 V loop source supplies drops of 5 V and 7 V. Find the remaining voltage drop.", "6 V", ["V", "mV", "kV"], 0.01, "easy"),
    ("circuit-analysis", "Thevenin and Norton", "Norton current", "A Thevenin equivalent has 12 V and 6 ohm. Find its Norton current.", "2 A", ["A", "mA"], 0.001, "medium"),
    ("transient-circuits", "RC transients", "RC time constant", "Find the time constant for R = 10 kohm and C = 100 microfarad.", "1 s", ["s", "ms"], 0.01, "medium"),
    ("transient-circuits", "RL transients", "RL time constant", "Find the time constant for L = 0.5 H and R = 10 ohm using τ = L/R.", "0.05 s", ["s", "ms"], 0.001, "medium"),
    ("ac-circuits", "Complex impedance", "Inductive reactance", "Find the inductive reactance at 50 Hz for L = 0.1 H. Use X_L = 2πfL.", "31.416 ohm", ["ohm", "kohm"], 0.05, "medium"),
    ("three-phase-systems", "Balanced power", "Three-phase real power", "A balanced load has line voltage 400 V, line current 10 A, and power factor 0.8. Find real power using P = √3 V_L I_L pf.", "5542.56 W", ["W", "kW"], 5.0, "medium"),
    ("electrical-machines", "Transformers", "Ideal transformer voltage", "An ideal transformer has N1/N2 = 5 and primary voltage 230 V. Find secondary voltage.", "46 V", ["V", "mV", "kV"], 0.01, "easy"),
    ("power-electronics", "DC-DC converters", "Ideal buck converter", "An ideal buck converter has input 100 V and duty ratio 0.4. Find average output voltage.", "40 V", ["V", "mV", "kV"], 0.01, "medium"),
    ("per-unit-systems", "Base quantities", "Base current", "For a single-phase base of 10 kVA and 200 V, find base current using Ibase = Sbase/Vbase.", "50 A", ["A", "mA"], 0.01, "medium"),
    ("transmission-lines", "Voltage regulation", "Percent voltage regulation", "A feeder is 240 V no-load and 228 V full-load. Find regulation as (Vnl−Vfl)/Vfl × 100.", "5.263", [], 0.02, "medium"),
    ("power-quality", "Power factor correction", "Apparent power", "A load consumes 8 kW at power factor 0.8. Find apparent power.", "10 kW", ["W", "kW"], 0.01, "easy"),
    ("industrial-electrical-systems", "Motor starting", "Motor input power", "A motor draws 12 A from 230 V single phase at power factor 0.75. Find real input power.", "2070 W", ["W", "kW"], 2.0, "medium"),
]
